# Server configuration
server.port=8080

# Spring Thymeleaf configuration
# Disable caching so changes to index.html are instantly visible without restarting during development
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
